### ISSUE TITLE
ESG檢測儀網站前台工作項目統整

### ISSUE THREAD

**Issue by qyke** [gcaa-org-tw/thaubing-esg#130]
### 工作項目
本處統整工作項目清單，細節另外開至其他issue中

本次使用的[Figma](https://www.figma.com/file/rpSC4798yFBjlI8SLLcrLz/ESG-%E6%AA%A2%E6%B8%AC%E5%84%80?node-id=819%3A701)
總統盃[討論紀錄](https://docs.google.com/document/d/1TTISVjeZA9w9Fjf7op8FVi4IQlbrNR4iuR0oso15syQ/edit?usp=sharing)

- [x] [首頁_版面調整](https://github.com/gcaa-org-tw/thaubing-esg/issues/125)
- [x] [首頁_歷年碳排變化+BAU趨勢_依產業別](https://github.com/gcaa-org-tw/thaubing-esg/issues/126)
- [x] [首頁_歷年碳排變化+目標減量_依產業別](https://github.com/gcaa-org-tw/thaubing-esg/issues/127)
- [x] [首頁_歷年碳排變化+BAU趨勢+目標減量_不同產業比較](https://github.com/gcaa-org-tw/thaubing-esg/issues/131)
- [x] [公司頁_歷年碳排變化+BAU趨勢+目標減量](https://github.com/gcaa-org-tw/thaubing-esg/issues/128)
- [x] [各文字區塊撰寫](https://github.com/gcaa-org-tw/thaubing-esg/issues/129)

### 說明／補充／備註

**Comment by ddio** [comment]
這張看起來沒有額外的工作？想問 @qyke 開這張的目的是什麼呢？

如果是純粹條列工作的話：

1. 可以善用 [project](https://github.com/orgs/gcaa-org-tw/projects/) 或 [milestone](https://github.com/gcaa-org-tw/thaubing-esg/milestone/)
2. 如果包含非程式類、無須和 github 整合的工作，可以善用其他專案管理服務

如果確定沒有其他用途的話，再麻煩 @qyke  把這張票關掉囉～
