### ISSUE TITLE
指標資料總清單

### ISSUE THREAD

**Issue by chengh42** [gcaa-org-tw/thaubing-esg#15]
詳見[2021年8月27日_指標討論會_會議紀錄 (google doc)](https://bit.ly/3zqvPrh)

## 指標總表

各項指標後方`［］`內列的是資料來源或說明；關於各指標的具體工作項目另列為 Issue，見 #1

### 環境 (E)

- [ ] 溫室氣體排放量［企業CSR會揭露到不同範疇］
    - [ ] 範疇一［[環保署／溫室氣體年排放量](https://data.epa.gov.tw/dataset/ghg_p_01)］
    - [ ] 範疇二［[環保署／溫室氣體年排放量](https://data.epa.gov.tw/dataset/ghg_p_01)］
    - [ ] 範疇三［部分企業CSR報告會公開］
- [ ] 能源
    - [ ] 總用電量［資料這次會要，但不一定有］
    - [ ] 再生能源用電量［部分企業CSR報告會公開］
- [ ] 用水量（取水量）［資料這次會要，但不一定有］
- [ ] 廢棄物管理 — 廢棄物項目及量［應該有資料，待確認］
- [ ] 污染管理
    - [ ] 空氣污染物［[環保署／各工廠空氣污染物排放資料](https://data.epa.gov.tw/dataset/ems_p_08)］
    - [ ] 排放水量［[環保署／水污染源許可及申報資料](https://data.gov.tw/dataset/106598)］
    - [ ] 毒化物排放項目及量［[環保署／毒性化學物質許可證資料](https://data.epa.gov.tw/dataset/ems_p_46)］
    - [ ] 違反環境法規紀錄［[環保署／列管事業污染源裁處資料](https://data.epa.gov.tw/dataset/ems_p_46)］

### 社會 (S)

- [ ] 員工人數
    - [ ] 性別比
    - [ ] 本外勞比
    - [ ] 新進率／離職率
- [x] 薪資［[證交所公開資訊觀測站／非擔任主管職務之全時員工薪資資訊](https://mops.twse.com.tw/mops/web/t100sb15)］
- [ ] 工時（待確認）
- [ ] 違反勞動法規紀錄［有資料，區分不同法規］
- [ ] 職業健康與安全
    - [ ] 重大職災［[勞動部／重大職業災害公開網](https://data.gov.tw/dataset/126835)］
    - [ ] 工安事故

### 治理 (G)

- [x] 資本額［[財政部／全國營業(稅籍)登記資料集](https://data.gov.tw/dataset/9400)］
- [ ] 供應鏈透明及管理（名單、管理機制）
- [ ] 社會關係（公害糾紛或陳情紀錄）
- [ ] 公司治理評鑑層級［sustaihub永訊智庫］
- [ ] 是否產製CSR報告［sustaihub永訊智庫 + [證交所公開資訊觀測站／上市櫃公司出具企業社會責任報告書情形](https://mops.twse.com.tw/mops/web/t100sb11)］
    - [ ] 是否揭露不利資訊［從違規紀錄查看，再反推］
- [x] 收入、成本與淨利（財報、資產）（[證交所公開資訊觀測站／合併財務報表](https://mops.twse.com.tw/mops/web/t163sb01)） 
- [ ] 稅務透明度［資料這次會要，但不一定有］
    - [ ] 租稅減免
    - [ ] 補助、補貼
- [ ] ISO認證（[ISO 獲證企業查詢](https://chinesebestiso.weebly.com/iso-295543565720225269892659735426.html)；僅有自主揭露的公司，僅能用英文查詢）
- [ ] 弊案（新聞資訊）

**Comment by chengh42** [comment]
有關 #5 的疑問 － 商業銀行（例：5847 玉山商業銀行股份有限公司）需要或可以以「利息收入」、「利息費用」作為替代科目名稱嗎？
